# Generated by Django 4.0.2 on 2022-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('latitude', models.FloatField(max_length=50)),
                ('longitude', models.FloatField(max_length=50)),
            ],
        ),
    ]
